-- This file was autogenerated with make_lua.js from data within the supinic/supibot repo
-- If you run the script your changes will be lost
return {
    -- all flags: "BLOCK", "DEVELOPER", "EXTERNAL_INPUT", "MENTION", "META", "NON_NULLABLE", "OPT_OUT", "OWNER_OVERRIDE", "PING", "PIPE", "ROLLBACK", "SKIP_BANPHRASE", "SUPINICS_ONLY", "SYSTEM", "WHITELIST"
    -- unwhitelisted #supinic special commands are: current, necrodancer, playsound, songrequest, songrequestqueue, streamgames, texttospeech, when, wrongsong
    excluded_flags={ "WHITELIST" },
    definitions={
        {
            name="%",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="8ball",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="9gag",
            aliases={ "gag" },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="about",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="accountage",
            aliases={ "accage" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="addbetween",
            aliases={ "ab" },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="afk",
            aliases={ "gn", "brb", "shower", "food", "lurk", "poop", "💩", "work", "study", "nap" },
            params={  },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="alias",
            aliases={ "$" },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "PIPE", "META" },
            
            subcommands={ 
                {
                    name="add",
                    aliases={ "create" },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="upsert",
                    aliases={ "addedit" },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="check",
                    aliases={ "list", "code", "spy" },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="publish",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="unpublish",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="copy",
                    aliases={ "copyplace" },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="describe",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="link",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="delete",
                    aliases={ "remove" },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="rename",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="restrict",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="unrestrict",
                    aliases={  },
                    pipe=true,
                    eat_before_sub_command=0
                }, 
                {
                    name="run",
                    aliases={ "try" },
                    pipe=true,
                    eat_before_sub_command=0
                } },
        
            eat_before_sub_command=0
        },
        {
            name="aliasbuildingblock",
            aliases={ "abb" },
            params={ { name="amount", type="number" }, { name="em", type="string" }, { name="errorMessage", type="string" }, { name="excludeSelf", type="boolean" }, { name="regex", type="regex" }, { name="replacement", type="string" } },
            flags={ "EXTERNAL_INPUT", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="artflow",
            aliases={ "rafi", "randomartflowimage" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="atop",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="automodcheck",
            aliases={ "amc" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="badapplerendition",
            aliases={ "badapple", "bar" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="ban",
            aliases={ "unban" },
            params={ { name="all", type="boolean" }, { name="channel", type="string" }, { name="clear", type="boolean" }, { name="command", type="string" }, { name="index", type="number" }, { name="invocation", type="string" }, { name="multiplier", type="number" }, { name="type", type="string" }, { name="string", type="string" }, { name="user", type="string" } },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="bancheck",
            aliases={ "bc" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="beefact",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="block",
            aliases={ "unblock" },
            params={ { name="channel", type="string" }, { name="command", type="string" }, { name="platform", type="string" }, { name="user", type="string" } },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="bot",
            aliases={  },
            params={ { name="channel", type="string" }, { name="mode", type="string" }, { name="url", type="string" } },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="botsubs",
            aliases={  },
            params={ { name="channel", type="string" }, { name="channelsOnly", type="boolean" }, { name="emotesOnly", type="boolean" } },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="chan",
            aliases={ "4chan", "textchan", "filechan", "imagechan" },
            params={ { name="regex", type="regex" }, { name="textOnly", type="string" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="channelfounderlist",
            aliases={ "cfl", "founders" },
            params={ { name="includeDates", type="boolean" }, { name="subStatus", type="boolean" } },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="chatneighbour",
            aliases={ "cn" },
            params={  },
            flags={ "BLOCK", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="check",
            aliases={  },
            params={ { name="index", type="number" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="checkem",
            aliases={ "CheckEm", "check'em" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="code",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="coinflip",
            aliases={ "cf" },
            params={ { name="fail", type="boolean" } },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="comment",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="commitcount",
            aliases={ "FarmingCommits" },
            params={ { name="since", type="date" } },
            flags={ "DEVELOPER", "MENTION", "NON_NULLABLE", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="cookie",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE", "ROLLBACK" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="copypasta",
            aliases={  },
            params={ { name="allowAsciiArt", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="corona",
            aliases={ "covid" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="countline",
            aliases={ "cl" },
            params={  },
            flags={ "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="countlinechannel",
            aliases={ "clc" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="countlinetotal",
            aliases={ "clt" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="crypto",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="cryptogame",
            aliases={ "cg" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="cryptowallet",
            aliases={ "cw" },
            params={ { name="type", type="string" } },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="currency",
            aliases={ "money" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="current",
            aliases={ "song" },
            params={ { name="linkOnly", type="boolean" } },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="dalle",
            aliases={  },
            params={ { name="id", type="string" }, { name="random", type="boolean" }, { name="search", type="string" } },
            flags={ "MENTION", "NON_NULLABLE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="dankdebug",
            aliases={ "js" },
            params={ { name="arguments", type="string" }, { name="errorInfo", type="boolean" }, { name="force", type="boolean" }, { name="function", type="string" }, { name="importGist", type="string" } },
            flags={ "EXTERNAL_INPUT", "DEVELOPER", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="dayoftheyear",
            aliases={ "doty", "monthoftheyear", "moty" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="debug",
            aliases={  },
            params={ { name="function", type="string" }, { name="importGist", type="string" } },
            flags={ "EXTERNAL_INPUT", "DEVELOPER", "PIPE", "SKIP_BANPHRASE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="define",
            aliases={ "def" },
            params={ { name="lang", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="devnull",
            aliases={ "/dev/null", "null" },
            params={  },
            flags={ "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="dictionary",
            aliases={ "dict" },
            params={ { name="index", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="discord",
            aliases={  },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="doesnotexist",
            aliases={ "dne" },
            params={ { name="linkOnly", type="boolean" }, { name="summary", type="boolean" }, { name="wordOnly", type="boolean" } },
            flags={ "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="downloadclip",
            aliases={ "dlclip" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="emotecheck",
            aliases={ "ec" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="epal",
            aliases={ "ForeverAlone" },
            params={ { name="game", type="string" }, { name="gender", type="string" }, { name="sex", type="string" } },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="externalbot",
            aliases={ "ebot" },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="faceit",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="fakenews",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="faq",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="fill",
            aliases={  },
            params={  },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="findraidstreams",
            aliases={ "frs" },
            params={ { name="haste", type="string" } },
            flags={ "DEVELOPER", "PIPE", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="firstchannelfollower",
            aliases={ "fcf" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="firstfollowedchannel",
            aliases={ "ffc" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="firstline",
            aliases={ "fl" },
            params={ { name="channel", type="string" }, { name="textOnly", type="boolean" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="firstseen",
            aliases={ "fs" },
            params={  },
            flags={ "BLOCK", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="followage",
            aliases={ "fa" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="formula1",
            aliases={ "f1" },
            params={ { name="season", type="number" }, { name="year", type="number" }, { name="weather", type="boolean" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="forsenCD",
            aliases={ "pajaCD" },
            params={  },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="forsenE",
            aliases={  },
            params={  },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="fuck",
            aliases={  },
            params={  },
            flags={ "BLOCK", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="funfact",
            aliases={ "ff" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gachi",
            aliases={ "gachilist", "gl" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gachicheck",
            aliases={ "gc" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gachisearch",
            aliases={ "gs", "gsa", "gachiauthorsearch" },
            params={ { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gamesdonequick",
            aliases={ "gdq" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="getprofilepicture",
            aliases={ "avatar", "pfp" },
            params={ { name="banner", type="boolean" }, { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="getvideodata",
            aliases={ "gvd" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gift",
            aliases={ "give" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="github",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="githubstatus",
            aliases={ "ghs" },
            params={  },
            flags={ "DEVELOPER", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="gpt",
            aliases={ "chatgpt" },
            params={ { name="context", type="string" }, { name="history", type="string" }, { name="model", type="string" }, { name="limit", type="number" }, { name="temperature", type="number" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="haHAA",
            aliases={ "4Head", "4HEad", "HEad" },
            params={ { name="search", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="help",
            aliases={ "commands", "helpgrep" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="horoscope",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="howlongtobeat",
            aliases={ "hltb" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="hug",
            aliases={  },
            params={  },
            flags={ "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="id",
            aliases={ "uid" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="inspireme",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="isdown",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="joinchannel",
            aliases={  },
            params={ { name="platform", type="string" }, { name="silent", type="boolean" } },
            flags={ "MENTION", "PIPE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="kanji",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="kiss",
            aliases={  },
            params={  },
            flags={ "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="knowyourmeme",
            aliases={ "kym" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="lastcommand",
            aliases={ "_" },
            params={ { name="input", type="boolean" } },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="lastline",
            aliases={ "ll", "lastmessage", "lm" },
            params={ { name="textOnly", type="boolean" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="lastseen",
            aliases={ "ls" },
            params={  },
            flags={ "BLOCK", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="link",
            aliases={  },
            params={  },
            flags={ "MENTION", "SYSTEM" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="liveuamap",
            aliases={ "lum", "luam" },
            params={ { name="lang", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="markov",
            aliases={  },
            params={ { name="debug", type="string" }, { name="dull", type="boolean" }, { name="channel", type="string" }, { name="exact", type="boolean" }, { name="stop", type="boolean" }, { name="words", type="number" } },
            flags={ "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="mastodon",
            aliases={  },
            params={ { name="instance", type="string" }, { name="random", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="math",
            aliases={  },
            params={ { name="fixed", type="boolean" }, { name="precision", type="number" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="mdn",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="me",
            aliases={ "/me" },
            params={  },
            flags={  },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="necrodancer",
            aliases={ "nd", "ndr", "necrodancerreset" },
            params={ { name="zone", type="string" } },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="news",
            aliases={  },
            params={ { name="country", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="npm",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="nutrients",
            aliases={  },
            params={ { name="specific", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="ocr",
            aliases={  },
            params={ { name="engine", type="number" }, { name="force", type="boolean" }, { name="lang", type="string" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="optout",
            aliases={ "unoptout" },
            params={  },
            flags={ "MENTION", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="origin",
            aliases={  },
            params={ { name="index", type="number" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="osrs",
            aliases={  },
            params={ { name="activity", type="string" }, { name="boss", type="string" }, { name="force", type="boolean" }, { name="rude", type="boolean" }, { name="seasonal", type="boolean" }, { name="skill", type="string" }, { name="virtual", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="pastebin",
            aliases={ "pbg", "pbp", "gist", "hbg", "hbp" },
            params={ { name="hasteServer", type="string" }, { name="force", type="boolean" }, { name="gistUser", type="string" }, { name="raw", type="boolean" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="pick",
            aliases={  },
            params={ { name="delimiter", type="string" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="ping",
            aliases={ "pang", "peng", "pong", "pung", "pyng" },
            params={  },
            flags={ "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="pingme",
            aliases={ "letmeknow", "lmk" },
            params={  },
            flags={ "BLOCK", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="pipe",
            aliases={  },
            params={ { name="_apos", type="object" }, { name="_char", type="string" }, { name="_force", type="boolean" }, { name="_pos", type="number" } },
            flags={ "MENTION", "PIPE", "META" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="playsound",
            aliases={ "ps" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="poe",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="pyramid",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="query",
            aliases={ "wolframalpha", "wa" },
            params={ { name="imageSummary", type="boolean" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomalbum",
            aliases={ "ra" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomanimalfact",
            aliases={ "raf", "rbf", "rcf", "rdf", "rff" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomanimalpicture",
            aliases={ "rap", "rbp", "rcp", "rdp", "rfp" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomclip",
            aliases={ "rc" },
            params={ { name="author", type="string" }, { name="dateFrom", type="date" }, { name="dateTo", type="date" }, { name="limit", type="number" }, { name="linkOnly", type="boolean" }, { name="period", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomcocktail",
            aliases={ "cock", "drinks", "tail", "cocktail" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomcommandalias",
            aliases={ "rca" },
            params={ { name="body", type="string" }, { name="command", type="string" }, { name="createdAfter", type="date" }, { name="createdBefore", type="date" }, { name="description", type="string" }, { name="name", type="string" }, { name="user", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomdonger",
            aliases={ "rd" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomemoji",
            aliases={ "re" },
            params={  },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomemote",
            aliases={ "rem" },
            params={ { name="7tv", type="boolean" }, { name="animated", type="boolean" }, { name="bttv", type="boolean" }, { name="channel", type="string" }, { name="ffz", type="boolean" }, { name="follower", type="boolean" }, { name="global", type="boolean" }, { name="repeat", type="boolean" }, { name="regex", type="regex" }, { name="sub", type="boolean" }, { name="twitch", type="boolean" } },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomfilm",
            aliases={ "rf" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomgachi",
            aliases={ "rg" },
            params={ { name="fav", type="string" }, { name="linkOnly", type="boolean" }, { name="type", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomgeneratedmeme",
            aliases={ "rgm" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomhistoricevent",
            aliases={ "rhe" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randominstagram",
            aliases={ "rig" },
            params={ { name="rawLinkOnly", type="boolean" }, { name="postLinkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomline",
            aliases={ "rl", "rq" },
            params={ { name="textOnly", type="boolean" } },
            flags={ "BLOCK", "EXTERNAL_INPUT", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randommeal",
            aliases={ "rmeal" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randommeme",
            aliases={ "rm" },
            params={ { name="comments", type="boolean" }, { name="flair", type="string" }, { name="ignoreFlair", type="string" }, { name="linkOnly", type="boolean" }, { name="showFlairs", type="boolean" }, { name="skipGalleries", type="boolean" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randompastebin",
            aliases={ "rpb" },
            params={ { name="linkOnly", type="boolean" }, { name="syntax", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomsadcat",
            aliases={ "rsc" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomscp",
            aliases={ "rscp" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomuploadervideo",
            aliases={ "ruv" },
            params={ { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="randomword",
            aliases={ "rw" },
            params={ { name="endsWith", type="string" }, { name="regex", type="regex" }, { name="startsWith", type="string" } },
            flags={ "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="record",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="reload",
            aliases={  },
            params={ { name="skipUpgrade", type="boolean" } },
            flags={ "PIPE", "SKIP_BANPHRASE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="remind",
            aliases={ "notify", "remindme", "remindprivate", "privateremind" },
            params={ { name="after", type="string" }, { name="at", type="string" }, { name="on", type="string" }, { name="private", type="boolean" } },
            flags={ "BLOCK", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="reset",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE", "SYSTEM" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="restart",
            aliases={  },
            params={  },
            flags={ "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="resumeafk",
            aliases={ "rafk", "cafk", "continueafk" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="roll",
            aliases={ "dice" },
            params={ { name="textOnly", type="boolean" } },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="russianarmylosses",
            aliases={ "ral" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="russianroulette",
            aliases={ "rr" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="schedule",
            aliases={  },
            params={  },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="set",
            aliases={ "unset" },
            params={ { name="from", type="string" } },
            flags={ "MENTION", "OWNER_OVERRIDE", "PIPE" },
            
            subcommands={ 
                {
                    name="reminder",
                    aliases={ "remind", "reminders" },
                    parameter="ID",
                    pipe=true,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="suggestion",
                    aliases={ "suggest", "suggestions" },
                    parameter="ID",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="location",
                    aliases={  },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="gc",
                    aliases={  },
                    parameter="ID",
                    pipe=true,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="discord",
                    aliases={  },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="birthday",
                    aliases={ "bday" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="language",
                    aliases={ "lang" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="twitchlotto",
                    aliases={ "tl" },
                    parameter="arguments",
                    pipe=true,
                    
                    subcommands={ 
                        { name="Anime", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Animal", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Bait", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Body-fluids", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Borderline", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Disfigured", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Disturbing", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Drawn", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Furry", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Gore", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Hentai", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Human", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="None", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Porn", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Offensive", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Rendered", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Scat", aliases={}, pipe=true, eat_before_sub_command=0 }, 
                        { name="Softcore", aliases={}, pipe=true, eat_before_sub_command=0 } },
                
                    eat_before_sub_command=1
                }, 
                {
                    name="twitchlottodescription",
                    aliases={ "tld" },
                    parameter="arguments",
                    pipe=true,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="twitchlottoblacklist",
                    aliases={ "tlbl" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="instagram-nsfw",
                    aliases={ "rig-nsfw" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="reddit-nsfw",
                    aliases={ "rm-nsfw" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="twitch-lotto-nsfw",
                    aliases={ "twitchlotto-nsfw", "tl-nsfw" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="twitter-nsfw",
                    aliases={ "tweet-nsfw" },
                    parameter="arguments",
                    pipe=false,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="timer",
                    aliases={  },
                    parameter="arguments",
                    pipe=true,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                }, 
                {
                    name="trackfavourite",
                    aliases={ "tf", "track-fav", "trackfavorite", "track-favourite", "track-favorite" },
                    parameter="arguments",
                    pipe=true,
                    
                    subcommands=nil,
                
                    eat_before_sub_command=0
                } },
        
            eat_before_sub_command=0
        },
        {
            name="shoutout",
            aliases={ "so" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="shuffle",
            aliases={  },
            params={ { name="fancy", type="boolean" } },
            flags={ "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="simplesql",
            aliases={ "ssql" },
            params={  },
            flags={ "MENTION", "PIPE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="slots",
            aliases={  },
            params={ { name="pattern", type="string" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="songrequest",
            aliases={ "sr" },
            params={ { name="start", type="string" }, { name="end", type="string" }, { name="type", type="string" } },
            flags={ "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="songrequestqueue",
            aliases={ "srq", "queue" },
            params={  },
            flags={ "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="songrequestrandomgachi",
            aliases={ "gsr", "srg", "srrg" },
            params={ { name="fav", type="string" } },
            flags={ "SKIP_BANPHRASE", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="sort",
            aliases={  },
            params={  },
            flags={ "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="speedrun",
            aliases={  },
            params={ { name="category", type="string" }, { name="showCategories", type="boolean" }, { name="abbreviation", type="string" }, { name="abbr", type="string" }, { name="runner", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="stackoverflowsearch",
            aliases={ "stackoverflow", "sos" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="stalk",
            aliases={  },
            params={  },
            flags={ "BLOCK", "EXTERNAL_INPUT", "MENTION", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="statistics",
            aliases={ "stat", "stats" },
            params={ { name="recalculate", type="boolean" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="steamgameplayers",
            aliases={ "sgp" },
            params={ { name="gameID", type="string" } },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="stock",
            aliases={ "stocks", "stonks" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="stream",
            aliases={  },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SYSTEM", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="streamgames",
            aliases={ "games", "sg" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SYSTEM", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="streaminfo",
            aliases={ "si", "uptime", "vod" },
            params={ { name="summary", type="boolean" }, { name="youtube", type="string" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="subage",
            aliases={ "sa" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="subscribe",
            aliases={ "unsubscribe" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="suggest",
            aliases={ "suggestions" },
            params={ { name="amend", type="number" } },
            flags={ "MENTION", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="supibotupdates",
            aliases={  },
            params={  },
            flags={ "PING" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="test",
            aliases={  },
            params={ { name="boolean", type="boolean" }, { name="date", type="date" }, { name="number", type="number" }, { name="object", type="object" }, { name="regex", type="regex" }, { name="string", type="string" } },
            flags={ "DEVELOPER", "PIPE", "SKIP_BANPHRASE", "SYSTEM" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="texttospeech",
            aliases={ "tts" },
            params={ { name="lang", type="string" }, { name="language", type="string" }, { name="speed", type="number" } },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="texttransform",
            aliases={ "tt", "reversetexttransform", "rtt" },
            params={  },
            flags={ "EXTERNAL_INPUT", "NON_NULLABLE", "PIPE" },
            
            subcommands={ 
                {
                    name="bubble",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="fancy",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="upside-down",
                    aliases={ "flipped", "ud", "upsidedown" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="elite",
                    aliases={ "leet", "l33t", "1337" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="medieval",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="runic",
                    aliases={ "runes" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="superscript",
                    aliases={ "smol", "super" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="vaporwave",
                    aliases={ "vw", "vapor" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="cockney",
                    aliases={ "3Head" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="cowboy",
                    aliases={ "KKona", "KKonaW" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="outback",
                    aliases={ "KKrikey", "australian" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="capitalize",
                    aliases={ "cap" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="lowercase",
                    aliases={ "lc", "lower" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="uppercase",
                    aliases={ "uc", "upper" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="monkaOMEGA",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="OMEGALUL",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="owoify",
                    aliases={ "owo", "uwu", "uwuify" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="reverse",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="random",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="antiping",
                    aliases={ "unping" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="trim",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="explode",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="binary",
                    aliases={ "bin" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="morse",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="box",
                    aliases={ "boxes" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="spongebob",
                    aliases={ "mock", "mocking", "spongemock" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="typoglycemia",
                    aliases={ "tg", "jumble" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="official",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="base64",
                    aliases={ "b64" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="ascii",
                    aliases={  },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="hex",
                    aliases={ "hexadecimal" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="forsen",
                    aliases={ "forsencode" },
                    pipe=true,
                    subcommands=nil
                }, 
                {
                    name="spurdo",
                    aliases={ "fug", "Spurdo" },
                    pipe=true,
                    subcommands=nil
                } },
        
            eat_before_sub_command=0
        },
        {
            name="tf2",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="thesaurus",
            aliases={  },
            params={ { name="singleWord", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="time",
            aliases={  },
            params={  },
            flags={ "BLOCK", "MENTION", "NON_NULLABLE", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="top",
            aliases={  },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="topgames",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="topstreams",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="totalcountline",
            aliases={ "acl", "tcl" },
            params={  },
            flags={ "MENTION", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="trackreupload",
            aliases={ "tr" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="translate",
            aliases={  },
            params={ { name="confidence", type="boolean" }, { name="engine", type="string" }, { name="from", type="string" }, { name="to", type="string" }, { name="textOnly", type="string" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="transliterate",
            aliases={  },
            params={ { name="japaneseOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="truck",
            aliases={  },
            params={  },
            flags={ "BLOCK", "OPT_OUT", "PIPE", "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="tuck",
            aliases={ "gnkiss", "headpat" },
            params={  },
            flags={ "BLOCK", "OPT_OUT", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="twitchlotto",
            aliases={ "tl" },
            params={ { name="excludeChannel", type="string" }, { name="excludeChannels", type="string" }, { name="forceUnscored", type="boolean" }, { name="preferUnscored", type="boolean" } },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="twitchlottoexplain",
            aliases={ "tle" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="twitter",
            aliases={ "tweet" },
            params={ { name="includeReplies", type="boolean" }, { name="includeRetweets", type="boolean" }, { name="mediaOnly", type="boolean" }, { name="random", type="boolean" }, { name="textOnly", type="boolean" }, { name="trends", type="string" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="unmention",
            aliases={ "remention" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="unping",
            aliases={ "reping" },
            params={  },
            flags={ "MENTION" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="urban",
            aliases={  },
            params={ { name="index", type="number" } },
            flags={ "EXTERNAL_INPUT", "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="vanish",
            aliases={  },
            params={  },
            flags={ "SKIP_BANPHRASE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="videostats",
            aliases={  },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE", "WHITELIST" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="vote",
            aliases={ "poll" },
            params={  },
            flags={ "MENTION", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="weather",
            aliases={  },
            params={ { name="alerts", type="boolean" }, { name="format", type="string" }, { name="latitude", type="number" }, { name="longitude", type="number" }, { name="pollution", type="boolean" }, { name="radar", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="whatanimeisit",
            aliases={ "tracemoe" },
            params={  },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="whatemoteisit",
            aliases={ "weit" },
            params={ { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="when",
            aliases={  },
            params={  },
            flags={ "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="whisper",
            aliases={ "/w", "pm" },
            params={  },
            flags={  },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="wiki",
            aliases={  },
            params={ { name="lang", type="language" }, { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="wrongsong",
            aliases={ "ws" },
            params={  },
            flags={ "DEVELOPER", "MENTION", "PIPE", "SUPINICS_ONLY" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        },
        {
            name="youtubesearch",
            aliases={ "ys" },
            params={ { name="index", type="number" }, { name="linkOnly", type="boolean" } },
            flags={ "MENTION", "NON_NULLABLE", "PIPE" },
            
            subcommands=nil,
        
            eat_before_sub_command=0
        }
    },
}
